### ISSUE TITLE
Enable a system wide installation

### ISSUE THREAD

**Issue by tcsenpai** [arunsupe/semantic-grep#1]
When trying to move sgrep binary to /usr/local/bin (or anything in PATH, and even putting the repo folder in PATH), problems arise as the binary looks for the config.json file in the same directory is called from.

I would suggest a more dynamic approach to enabling a system wide installation, such as looking in $HOME/.config/semantic-grep/config.json or something similar, as I can certainly see sgrep as a useful system wide tool

**Comment by ylluminate** [comment]
Homebrew install for macOS would also be very useful both in this regard and for convenience/updatability.

**Comment by arunsupe** [comment]
Implemented better config handling. Now looks for config.json in "$HOME/.config/semantic-grep/", "/etc/semantic-grep/config.json", "./".

Homebrew install, and other distribution specific installs are a flattering idea. I don't have the know-how for it. But, if there is interest in making this widely available, I'd be happy to work on it (with a lot of help from the community).
