### ISSUE TITLE
(pedantic) cli arguments break convention

### ISSUE THREAD

**Issue by coljac** [arunsupe/semantic-grep#13]
May I suggest following the usual convention for short-form and long-form arguments?

```
 -m, --model_path string
        Path to the Word2Vec model file
...
  -t, --threshold float
        Similarity threshold for matching (default 0.7)
```

**Comment by arunsupe** [comment]
Thank you. Strongly agree. I have to learn how to do this using go's flag package. Will fix it before the next release.
