### ISSUE TITLE
Support go install

### ISSUE THREAD

**Issue by clipperhouse** [arunsupe/semantic-grep#15]
I think it should be possible to just use `go install` for this package? In the install script, I see the logic about putting things in the PATH etc, but that’s well documented on the Go site.

The model download prompt could also be moved into the app itself, yes? Or maybe a subcommand. Ditto creating a config file.

(In turn, supporting `brew install` shouldn’t be difficult either.)

Keep up the impressive work!

**Comment by arunsupe** [comment]
Great idea. I am new to go. I will look into how to do this.

Thank you also for fixing the word splitter. It now works correctly for any language.

**Comment by clipperhouse** [comment]
You might find this helpful: https://github.com/spf13/cobra

**Comment by arunsupe** [comment]
> I think it should be possible to just use `go install` for this package? In the install script, I see the logic about putting things in the PATH etc, but that’s well documented on the Go site.
> 
> The model download prompt could also be moved into the app itself, yes? Or maybe a subcommand. Ditto creating a config file.
> 
> (In turn, supporting `brew install` shouldn’t be difficult either.)
> 
> Keep up the impressive work!

I am looking into `go install`. It uses the repo's name as the name of the binary: `go install github.com/arunsupe/semantic-grep@v0.7.1`. Not sure how to make `go install` change the name to w2vgrep without me changing the name of the repo. Thoughts?

**Comment by clipperhouse** [comment]
I think that’s correct. I think renamed repositories will redirect automatically? I don’t believe there is a way to name the binary that’s not the directory name.

**Comment by sergeevabc** [comment]
This issue is not resolved actually, because

``` console

$ go install -ldflags="-s -w" github.com/arunsupe/semantic-grep@latest

go: downloading github.com/arunsupe/semantic-grep v1.0.0
go: github.com/arunsupe/semantic-grep@latest: version constraints conflict:
        github.com/arunsupe/semantic-grep@v1.0.0: parsing go.mod:
        module declares its path as: sgrep
                but was required as: github.com/arunsupe/semantic-grep
```

**Comment by arunsupe** [comment]
Thanks for noting this. I am able to reproduce it. Trying to fix, but cannot figure out how. There is no sgrep anywhere in the mod files or imports. Any help will be greatly appreciated.

**Comment by sergeevabc** [comment]
Dear @arunsupe, I am not a developer, but a bug hunter. My mission is to examine apps and identify their flaws, how to fix them is another story. Usually, Stackexchange Q&A sites such as Stackoverflow are a good place to find a recipe for any difficulty, especially related to computers. [Try this one](https://stackoverflow.com/questions/76446618/how-make-git-repo-install-with-go-install-command-and-retract-mistakenly-publi).
