### ISSUE TITLE
How well can this handle bad OCR / misspelled grep'ing?

### ISSUE THREAD

**Issue by ylluminate** [arunsupe/semantic-grep#4]
I frequently work with OCR'd and PDFs with bad OCR text. How well does this work with simply misspelled or generally wrongly and badly spelled words? Having the ability to find even proper words and thoughts in "train wreck" text would be incredibly useful.

**Comment by arunsupe** [comment]
Poorly. This program works by first mapping words to vectors using a word2vec model. The vast majority of words in the model are correctly spelt.

**Comment by ylluminate** [comment]
Very sad. Thanks for letting us know. I suppose a fork that takes a different more robust approach would be your preference vs integrating such into your efforts, correct?
