### ISSUE TITLE
Support other languages

### ISSUE THREAD

**Issue by asadal** [arunsupe/semantic-grep#9]
Hi,

I tested it against Korean text, but it didn't work.
Does it support search in non-English languages, for example, Korean?

**Comment by gukoff** [comment]
The currently used word2vec model is limited to [300k English words](https://github.com/eyaler/word2vec-slim). You can try your luck with [the larger word2vec model](https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?resourcekey=0-wjGZdNAUop6WykTtMip30g?) or the [model for your language of choice](https://fasttext.cc/docs/en/crawl-vectors.html). Generally, word2vec gets trained for a specific language.

**Comment by arunsupe** [comment]
Added support for multiple languages. A bit hackey - have to convert fasttext model vectors. Added a program to do the conversion. See example in the Readme, under section "Support for multiple languages"

**Comment by asadal** [comment]
Thanks for your kind answer. @gukoff @arunsupe :)

**Comment by arunsupe** [comment]
to make a korean model:

```bash
curl -s 'https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.ko.300.vec.gz' | gunzip -c | ./fasttext-to-bin -input - -output models/fasttext/cc.ko.300.bin
```

Then
```bash
curl -s 'https://www.gutenberg.org/cache/epub/5739/pg5739.txt' | sgrep.linux.amd64 -n -threshold 0.5 -model_path models/fasttext/cc.ko.300.bin '밥'
```
Output 
```
  Similarity: 0.5437
  1227:반찬 side dishes
  --
  Similarity: 1.0000
  1239:밥 cooked rice
```

**Comment by asadal** [comment]
Hi, @arunsupe 
I tested cc.ko.300.bin model, and it works good. :)
Thanks again. :)
